trigger:
-master

pool:
  name: LinuxPool

steps:
- checkout: self
- ContinueOnError: True
- TimeoutInMinutes: 10
- CancelTimeoutInMinutes: 1

- script:
    echo "linux-run-to-check-params"
    pwd
    ls -al
    du -sh | sort -hr
    echo "pipeline SUCCESS"
  displayName: " linux PPL C"

- bash: echo "PPL complete"
  displayName: 'Success'
